FROM alpine

RUN apk add --update nodejs npm

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm i -f

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]
