version: '3.8'

services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 8080:8080
    networks:
      - app
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - app
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    # volumes:
      # - ./frontend/build:/usr/share/nginx/html
      # - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      # - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - app
networks: 
  app:
    driver: bridge