version: '3.8'

services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 8080:8080
    networks:
      - app
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    restart: always
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /app/node_modules
      - /app/build
      - ./frontend:/app
      # - ./frontend/build:/usr/share/nginx/html
      # - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      # - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   container_name: certbot
  #   volumes:
  #     - etc-letsencrypt:/etc/letsencrypt
  #     - ./frontend/build:/usr/share/nginx/html
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html --email iskndrsmt@gmail.com --agree-tos --no-eff-email -d tochka.bbu.kg
  #   networks:
  #     - app
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - app
volumes:
  etc-letsencrypt:
networks: 
  app:
    driver: bridge