export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAILED = 'USERS_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAIL'

export const USER_UPLOAD_INFO_REQUEST = 'USER_UPLOAD_INFO_REQUEST'
export const USER_UPLOAD_INFO_SUCCESS = 'USER_UPLOAD_INFO_SUCCESS'
export const USER_UPLOAD_INFO_FAIL = 'USER_UPLOAD_INFO_FAIL'

export const USER_UPLOAD_INFO_TWO_REQUEST = 'USER_UPLOAD_INFO_TWO_REQUEST'
export const USER_UPLOAD_INFO_TWO_SUCCESS = 'USER_UPLOAD_INFO_TWO_SUCCESS'
export const USER_UPLOAD_INFO_TWO_FAIL = 'USER_UPLOAD_INFO_TWO_FAIL'
